apiVersion: v1
kind: Service
metadata:
  name: yuripereira-dash-service
  namespace: yuripereira
spec:
  selector:
    app: yuripereira-dash
  ports:
    - protocol: TCP
      port: 52064
      targetPort: 52064
      nodePort: 52064
  type: NodePort