---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-redis
  namespace: yuripereira
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: serverless-redis
  template:
    metadata:
      labels:
        app: serverless-redis
    spec:
      initContainers:
      - name: unzip-files
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /runtime/user/;
            base64 -d /runtime/zipfile > /runtime/user/handler.zip;
            unzip /runtime/user/handler.zip -d /runtime/user/;
        volumeMounts:
        - name: zipfile
          mountPath: /runtime
        - name: runtime
          mountPath: /runtime/user
      containers:
      - name: serverless-redis
        image: quay.io/yurilpbh/tp3_runtime:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 250M
        volumeMounts:
        - name: pyfile
          mountPath: "/runtime/usermodule.py"
          subPath: pyfile
        - name: env
          mountPath: "/runtime/.env"
          subPath: env
        - name: user
          mountPath: /runtime/user
        env:
        - name: REDIS_HOST
          value: "192.168.121.187"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          value: "metrics"
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
      - name: env
        configMap:
          name: pyfile
      - name: zipfile
        configMap:
          name: pyfile
      - name: user
        emptyDir: {}
